amend to allow the prompt to be skipped
adaptlearning/adapt-contrib-bookmarking pull request #25
Opened 2017-06-14 15:10 UTC by moloko

2017-06-14 15:20 UTC, tomgreenfield approved these changes

2017-06-14 15:21 UTC, brian-learningpool approved these changes

2017-06-14 15:30 UTC, oliverfoster requested changes

2017-06-14 15:30 UTC, oliverfoster commented on js/adapt-contrib-bookmarking.js
>      var Bookmarking = _.extend({
Can you change to:
```
var Bookmarking = Backbone.Controller.extend({

});

return new Bookmarking();

```

2017-06-14 15:44 UTC, tomgreenfield commented on js/adapt-contrib-bookmarking.js
>      var Bookmarking = _.extend({
Would need the framework dependency bumping to `2.0.18` if this goes in.

2017-06-14 15:45 UTC, oliverfoster commented on js/adapt-contrib-bookmarking.js
>      var Bookmarking = _.extend({
If you say so 👍

2017-06-14 18:09 UTC, moloko reviewed
need to set version to 2.1.0

2017-06-14 18:09 UTC, moloko commented on bower.json
> +  "version": "2.0.5",
oops this should actually be 2.1.0 now cause this is a new feature

2017-06-15 09:39 UTC, tomgreenfield approved these changes

2017-06-15 09:40 UTC, chetan-hajare approved these changes

2017-06-15 10:07 UTC, oliverfoster approved these changes

2017-06-15 10:46 UTC, merged